export const projects = [
  {
    id: 1,
    name: 'Todo App',
    description: 'Manage your daily tasks efficiently.',
  },
  {
    id: 2,
    name: 'Notes App',
    description: 'Take and organize notes.',
  },
  {
    id: 3,
    name: 'Workout Tracker',
    description: 'Track your workouts and progress.',
  },
];

export const tasks = [
  {
    id: '1',
    title: 'Reply to marketing emails',
    description: 'Respond to promotional emails before the offer expires.',
    importance: 4,
    urgency: 8,
    isCompleted: false,
  },
  {
    id: '2',
    title: 'Renew streaming subscription',
    description: 'Renew your streaming service before it expires.',
    importance: 3,
    urgency: 7,
    isCompleted: false,
  },
  {
    id: '3',
    title: 'RSVP to event invitation',
    description: 'Respond to the event invitation before the deadline.',
    importance: 5,
    urgency: 9,
    isCompleted: false,
  },
  {
    id: '4',
    title: 'Pick up dry cleaning',
    description: 'Collect clothes from the dry cleaner before closing.',
    importance: 4,
    urgency: 8,
    isCompleted: false,
  },
  {
    id: '5',
    title: 'Return library books',
    description: 'Return borrowed books before the due date.',
    importance: 5,
    urgency: 7,
    isCompleted: false,
  },
  {
    id: '6',
    title: 'Buy birthday card',
    description: 'Purchase a card before the birthday party.',
    importance: 4,
    urgency: 6,
    isCompleted: false,
  },
  {
    id: '7',
    title: 'Finish project report',
    description: 'Complete and submit the final project report to the manager.',
    importance: 9,
    urgency: 9,
    isCompleted: false,
  },
  {
    id: '8',
    title: 'Submit tax documents',
    description: 'Send required documents to the accountant.',
    importance: 9,
    urgency: 10,
    isCompleted: false,
  },
  {
    id: '9',
    title: 'Update resume',
    description: 'Add recent experience and skills to resume.',
    importance: 7,
    urgency: 4,
    isCompleted: false,
  },
  {
    id: '10',
    title: 'Review budget',
    description: 'Check monthly expenses and adjust the budget.',
    importance: 8,
    urgency: 5,
    isCompleted: false,
  },
  {
    id: '11',
    title: 'Read a book',
    description: 'Read at least 30 pages of a new novel.',
    importance: 4,
    urgency: 2,
    isCompleted: false,
  },
  {
    id: '12',
    title: 'Organize desk',
    description: 'Clean and organize the work desk.',
    importance: 3,
    urgency: 2,
    isCompleted: false,
  },
  {
    id: '13',
    title: 'Plan weekend trip',
    description: 'Research and plan activities for the upcoming weekend getaway.',
    importance: 5,
    urgency: 3,
    isCompleted: false,
  },
  {
    id: '14',
    title: 'Research new laptop',
    description: 'Compare specs and prices for a new laptop.',
    importance: 5,
    urgency: 2,
    isCompleted: false,
  },
  {
    id: '15',
    title: 'Organize photos',
    description: 'Sort and organize digital photos from last year.',
    importance: 3,
    urgency: 1,
    isCompleted: false,
  },
  {
    id: '16',
    title: 'Write blog post',
    description: 'Draft and publish a new blog post.',
    importance: 5,
    urgency: 3,
    isCompleted: false,
  },
  {
    id: '17',
    title: 'Meditate',
    description: 'Spend 15 minutes meditating.',
    importance: 4,
    urgency: 2,
    isCompleted: false,
  },
  {
    id: '18',
    title: 'Respond to group chat',
    description: 'Reply to urgent messages in the group chat.',
    importance: 3,
    urgency: 8,
    isCompleted: false,
  },
  {
    id: '19',
    title: 'Order office supplies',
    description: 'Place an order before the end-of-day deadline.',
    importance: 5,
    urgency: 7,
    isCompleted: false,
  },
  {
    id: '20',
    title: 'Book taxi for airport',
    description: 'Book a taxi before the time slot is unavailable.',
    importance: 4,
    urgency: 9,
    isCompleted: false,
  },
  {
    id: '21',
    title: 'Confirm dinner reservation',
    description: 'Call the restaurant to confirm your reservation.',
    importance: 4,
    urgency: 7,
    isCompleted: false,
  },
  {
    id: '22',
    title: 'Pay parking ticket',
    description: 'Pay the ticket before the late fee applies.',
    importance: 5,
    urgency: 8,
    isCompleted: false,
  },
  {
    id: '23',
    title: 'Water plants',
    description: 'Water all indoor and outdoor plants.',
    importance: 5,
    urgency: 6,
    isCompleted: false,
  },
  {
    id: '24',
    title: 'Clean fridge',
    description: 'Throw out expired food and clean the refrigerator.',
    importance: 5,
    urgency: 4,
    isCompleted: false,
  },
  {
    id: '25',
    title: 'Donate clothes',
    description: 'Sort and donate unused clothes to charity.',
    importance: 6,
    urgency: 3,
    isCompleted: false,
  },
];
